src/pages/index.astro

Changed the icons in the home page to EMBL green so they match the cards

Changed the colours of the home page icons

---

src/pages/image/[uuid].astro

Quick fix to correct URI for iframe for vizarr on image page

Fix URI for vizarr iframe

---

src/pages/image/[uuid].astro

itk and vizarr buttons now work
Commented out download file button since that will require a bit more effort to get working. Will focus on the copy URL button next but it seems more complicated.

fixed visualizer button urils on image pages

---

src/pages/image/[uuid].astro

Button switches from Copy OME-Zarr URI -> URI Copied

copy vizarrr url button works

---

src/data/bia-study-metadata.json
src/pages/dataset/[accession_id].astro

Addes total image count, file count, and list of file types to the study pages.
Note that the numbers seem really weird, and possibly the wrong way round - I think the front end code is correct, but need to double check the data values are being generated correctly (and not e.g. the wrong way round)

added total counts to study pages

---

src/components/BrowseDatasetCard.astro
src/components/Card.astro
src/components/DatasetDetail.astro
src/components/DatasetInfo.astro
src/data/metadata-field-name-mapping.json
src/pages/dataset/[accession_id].astro
src/pages/datasets.astro

https://app.clickup.com/t/8696kwqcg
Update study data
Update code to get data to fetch study component info from the dataset section
put growth protocols in the correct location
https://deploy-preview-37--bia-beta-website.netlify.app/bioimage-archive/dataset/s-biad1075/ has growth protocols
Added a basic filter on the page

added new json and fetch data from dataset field

---

src/components/DatasetInfo.astro
src/data/metadata-field-name-mapping.json

and added correlation method
Thanks aybuke for noticing the missing sections

fix lack of display of annotation method section 

---

src/pages/datasets.astro

The clickup ticket for this PR: https://app.clickup.com/t/86971t4j1

added total number of studies, files and images calculation and display

---

src/components/ImageRow.astro
src/pages/dataset/[accession_id].astro
src/pages/image/[uuid].astro

Will be updating the defaults of the exporter to match

update export data file names to be clearer and more consistent with one another

---

src/components/ai-playground/BenchmarkingTable.astro
src/data/ai-dataset-benchmarking/model-dataset-table.json
src/pages/ai-playground/dataset/[accession_id].astro
src/pages/ai-playground/model/[model_name].astro

https://app.clickup.com/t/8697kqz34

added benchmarking tables to ai playground

---

src/components/DatasetDetail.astro
src/components/SharedJSFunctions.js
src/components/ai-playground/DatasetInfo.astro
src/components/ai-playground/ModelPredictionTable.astro
src/data/ai-dataset-benchmarking/additional-study-metadata.json
src/pages/ai-playground/dataset/[accession_id].astro
src/pages/ai-playground/model/[model_name].astro
src/pages/dataset/[accession_id].astro

See: https://app.clickup.com/t/8697mhg4g

filtered dataset information and added annotation info for ai benchmarking pages

---

src/components/cards/BrowseDatasetCard.astro
src/pages/datasets.astro
src/styles/toggle.css

Ticket: https://app.clickup.com/t/86979vxbt

add filter for has image toggle on dataset page

---

src/data/ai-dataset-benchmarking/additional-study-metadata.json
src/data/ai-dataset-benchmarking/model-metadata.json

Updates to model generation JSON to include the model task, and to additional study metadata JSON to include a hero image and a hero ground truth image.
https://app.clickup.com/t/8697tq1u8

Updated JSON files

---

src/components/ai-benchmarking/BenchmarkingTable.astro
src/components/ai-benchmarking/ModelPredictionTable.astro
src/components/cards/AIModelCard.astro
src/pages/galleries/ai/models.astro

https://app.clickup.com/t/8697qy03v

added filter toggle for model cards plus minor style changes and fixes

---

package.json
public/robots.txt
src/layouts/BaseLayout.astro
src/layouts/Layout.astro
src/pages/index.astro

https://app.clickup.com/t/8697xtz1a
Needs to be in website root (but website base is bioimage-archive)
https://developers.google.com/search/docs/crawling-indexing/robots/create-robots-txt

Test add robots.txt after build

---

src/pages/help/about-the-new-website.mdx
src/pages/index.astro

ticket: https://app.clickup.com/t/86983dc53

added feeback form link

---

src/layouts/BaseLayout.astro

added scroll padding to take into account navbar height when clicking on table of contents elements
can rebase after other PR merge so there is at least a deploy preview with all the changes.

added scroll padding to most pages

---

src/data/collections/spatialomics.json
src/pages/galleries/spatialomics/study/[accessionID].astro

related to: https://app.clickup.com/t/8697xk2xh

added omics and code links to SO gallery pages

---

package-lock.json
src/components/SharedJSFunctions.js
src/components/cards/BrowseStudyCard.astro
src/pages/galleries/ai/ai-ready-study/[accessionID].astro
src/pages/galleries/ai/image/[uuid].astro

This pull request refactors the handling of "annotation type" data to make it more robust and consistent across the AI-ready study and image gallery pages.
- **Refactored `getAnnotationType` function:** The logic has been completely rewritten to handle various JSON structures, including nested arrays and direct string values. It now correctly parses and normalizes annotation type data from both `additional_metadata` and the `annotation_process` fields.
- **Improved data fallback:** The function now falls back to the `method_type` field from `annotation_process` if no `annotation_type` is found, ensuring we display as much information as possible.
- **Updated display logic:** The display of annotation types in `BrowseStudyCard.astro`, `[accessionID].astro`, and `[uuid].astro` has been …

Tidy up AI-ready study cards

---

src/data/metadata-field-name-mapping.json

https://app.clickup.com/t/869a9h0wc

Tidy up field names on study pages
